vse: &vse
  docker:
    - image: circleci/node:8.11.3
    
vseansible: &vseansible
  docker:
    - image: circleci/python:3.6.2

version: 2.1
jobs:
  build:
    <<: *vse
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
         root: .
         paths:
            - .
  deploy:
     <<: *vseansible
     steps:
        - attach_workspace:
           at: .
        - run: sudo pip install --upgrade pip
        - run: sudo pip install ansible boto boto3
        - run:  
           command: | export AWS_ACCESS_KEY_ID="$access"
                      export AWS_SECRET_ACCESS_KEY="$secret"
                      export AWS_SECURITY_TOKEN="$token"
                      ansible-playbook ./.circleci/aws_deploy.yml --user ubuntu --ssh-common-args='-o StrictHostKeyChecking=no'

workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
         requires:
            - build
         filters:
            branches:
               only: 
                 - master
                 - dev

